### ISSUE TITLE
readBPM - SNPIndex and SNPNames missing

### ISSUE THREAD

**Issue by grafab** [HenrikBengtsson/illuminaio#5]
The indices in the IDAT file need to be "translated" to the marker names, in order to make sense out of the data.
readBPM does not output SNPIndex and SNPNames. The lines in the code are commented out. Uncommenting them results in "Error: cannot allocate vector of size 7.0 Gb". Is there any way to get the marker names from the BPM file without using GenomeStudio?

**Comment by HenrikBengtsson** [comment]
Thanks for letting us know.  This seems weird, but when I'm looking at the code for `readBPM()` I got even more puzzled myself, so I created Issue #6.  It looks like the BPM parser is incomplete.  When that is fixed, I'd guess this issue will more or less be automatically resolved.   I cannot give you a timeline at this point.  I've very little time myself to work on illuminaio these days, but maybe someone else will be able to figure it out.

**Comment by kasperdanielhansen** [comment]
Look at the Illumina 450k annotation packages from Bioconductor,
specifically
  IlluminaHumanMethylation450kmanifest
  IlluminaHumanMethylation450kanno.ilmn12.hg19

If you don't trust the packages, there is code for parsing the CSV version
of the BPM file in the packages "scripts" directory.

Best,
Kasper

**Comment by HenrikBengtsson** [comment]
Hi @grafab,

we decided to deprecate `readBPM()` because it turns out that it is not even near being a proper parser and it someone slipped in to illuminaio when our guards were down.  For details, see Issue #6.

We'll most likely not add real support for `readBPM()` anytime soon (unless contributed by someone).  Sorry about that.

See Tim's and Kasper's comments on how to parse BPM files and/or get same data from elsewhere.
